#!/usr/bin/env bash
#displays best school 10 times but on the 9th iteration ,displays best school and then hi, using a while and if statement.

count=1
while [ $count -le 10 ]; do
  if [ $count -eq 9 ]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  ((count++))  
done
