#!/usr/bin/env bash
#this script does the following displays bad luck for the 4th loop iteration
# displays good luck  the 8th loop iteration
#displays Best School  the other iterations

count=1
while [ $count -le 10 ]; do
  if [ $count -eq 4 ]; then
    echo "Bad luck"
  elif [ $count -eq 8 ]; then
    echo "Good luck"
  else
    echo "Best School"
  fi
  ((count++))  
done
