#!/usr/bin/env bash
#the script does the following ,displays 4 and then bad luck from China for the 4th loop iteration
displays 9 and then bad luck from Japan for the 9th loop iteration
displays 17 and then bad luck from Italy for the 17th loop iteration


count=1
while [ $count -le 17 ]; do
  case $count in
    4)
      echo "4"
      echo "Bad luck from China"
      ;;
    9)
      echo "9"
      echo "Bad luck from Japan"
      ;;
    17)
      echo "17"
      echo "Bad luck from Italy"
      ;;
    *)
      echo $count
      ;;
  esac
  ((count++))  
done
